/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crawlspellsuccesscalc;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Игорь
 */
public class MainCalcFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainCalcFrame
     */
    private int size;
    private int shieldtype;
    private int nmagicSkills;
    
    public MainCalcFrame() {
        initComponents();
        size=CrawlCalculator.NORMALSPECIES;
        shieldtype=CrawlCalculator.NOSHIELD;
        nmagicSkills=1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        SkillCComboBox = new javax.swing.JComboBox();
        SpellcastingSpinner = new javax.swing.JSpinner();
        StrSpinner = new javax.swing.JSpinner();
        IntSpinner = new javax.swing.JSpinner();
        Skill1Spinner = new javax.swing.JSpinner();
        Skill2Spinner = new javax.swing.JSpinner();
        Skill3Spinner = new javax.swing.JSpinner();
        SpeciesComboBox = new javax.swing.JComboBox();
        ShieldComboBox = new javax.swing.JComboBox();
        EncumbranceSpinner = new javax.swing.JSpinner();
        ShieldsSpinner = new javax.swing.JSpinner();
        ArmorSpinner = new javax.swing.JSpinner();
        ResultLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        SpellLvlSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        WildMagicCheckBox = new javax.swing.JCheckBox();
        WildMagicSpinner = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        WizardryCheckBox = new javax.swing.JCheckBox();
        WizardrySpinner = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        HatCheckBox = new javax.swing.JCheckBox();
        VehumetCheckBox = new javax.swing.JCheckBox();
        VehumetSpinner = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        SubduedMagicCheckBox = new javax.swing.JCheckBox();
        SubduedMagicSpinner = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Вычисление шанса мискаста");

        jButton1.setText("Вычислить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SkillCComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 навык", "2 навыка", "3 навыка" }));
        SkillCComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SkillCComboBoxItemStateChanged(evt);
            }
        });

        SpellcastingSpinner.setModel(new SpinnerNumberModel(0,0,27,0.5));

        StrSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        IntSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        Skill1Spinner.setModel(new SpinnerNumberModel(0,0,27,0.5));

        Skill2Spinner.setModel(new SpinnerNumberModel(0,0,27,0.5));
        Skill2Spinner.setEnabled(false);

        Skill3Spinner.setModel(new SpinnerNumberModel(0,0,27,0.5));
        Skill3Spinner.setEnabled(false);

        SpeciesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Spriggan", "Kobold, Halfling", "Ogre, Troll, Centaur, Naga, Formicid", "Other" }));
        SpeciesComboBox.setSelectedIndex(3);
        SpeciesComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SpeciesComboBoxItemStateChanged(evt);
            }
        });

        ShieldComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Нет щита", "Buckler", "Shield", "Large Shield" }));
        ShieldComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ShieldComboBoxItemStateChanged(evt);
            }
        });

        EncumbranceSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        ShieldsSpinner.setModel(new SpinnerNumberModel(0,0,27,0.5));

        ArmorSpinner.setModel(new SpinnerNumberModel(0,0,27,0.5));

        ResultLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setText("Размер персонажа");

        jLabel4.setText("Размер щита");

        jLabel5.setText("Armor Encumbrance rating");

        jLabel6.setText("Shield skill");

        jLabel8.setText("Armor skill");

        jLabel9.setText("Str");

        jLabel10.setText("Int");

        jLabel12.setText("Magic skills");

        jLabel13.setText("От скольки навыков зависит магия");

        jLabel14.setText("Spellcasting");

        SpellLvlSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9, 1));

        jLabel2.setText("Уровень магии");

        WildMagicCheckBox.setText("Wild Magic mutation");
        WildMagicCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                WildMagicCheckBoxItemStateChanged(evt);
            }
        });

        WildMagicSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));
        WildMagicSpinner.setEnabled(false);

        jLabel11.setText("Mut level");

        WizardryCheckBox.setText("Wizardry items");
        WizardryCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                WizardryCheckBoxItemStateChanged(evt);
            }
        });

        WizardrySpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9, 1));
        WizardrySpinner.setEnabled(false);

        jLabel15.setText("Num of items");

        HatCheckBox.setText("Hat of the High Council");

        VehumetCheckBox.setText("Vehumet worshipper");
        VehumetCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                VehumetCheckBoxItemStateChanged(evt);
            }
        });

        VehumetSpinner.setModel(new javax.swing.SpinnerNumberModel(6, 0, 6, 1));
        VehumetSpinner.setEnabled(false);

        jLabel16.setText("Piety *");

        jLabel17.setText("(and Vehumet supports this spell)");

        SubduedMagicCheckBox.setText("Subdued Magic mutation");
        SubduedMagicCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SubduedMagicCheckBoxItemStateChanged(evt);
            }
        });

        SubduedMagicSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));
        SubduedMagicSpinner.setEnabled(false);

        jLabel18.setText("Mut level");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SpellLvlSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Skill2Spinner)
                                                .addComponent(Skill1Spinner)
                                                .addComponent(SkillCComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(SpellcastingSpinner)
                                                .addComponent(Skill3Spinner, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel17)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(WildMagicSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(WildMagicCheckBox)
                                                        .addComponent(jLabel12))
                                                    .addGap(2, 2, 2))
                                                .addComponent(VehumetCheckBox, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(VehumetSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                                        .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SubduedMagicCheckBox)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel18)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(SubduedMagicSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(HatCheckBox)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(StrSpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                .addComponent(IntSpinner, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(ResultLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(WizardryCheckBox)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(SpeciesComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ShieldComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EncumbranceSpinner))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(WizardrySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ShieldsSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                    .addComponent(ArmorSpinner)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(295, 295, 295)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpellcastingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StrSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IntSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpellLvlSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SkillCComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpeciesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ShieldComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ShieldsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EncumbranceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ArmorSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(34, 34, 34)
                                .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                                .addComponent(ResultLabel)
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Skill1Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Skill2Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Skill3Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(WildMagicCheckBox)
                                            .addComponent(WizardryCheckBox)
                                            .addComponent(SubduedMagicCheckBox))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(WildMagicSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)
                                            .addComponent(WizardrySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15)
                                            .addComponent(SubduedMagicSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(VehumetCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17))
                                    .addComponent(HatCheckBox))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(VehumetSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SkillCComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SkillCComboBoxItemStateChanged
        //ResultLabel.setText(evt.getItem().toString());
        //int n=SkillCComboBox.getItemCount();
        int i=0;
        for(;!SkillCComboBox.getItemAt(i).equals(evt.getItem());i++){}
       
        Skill2Spinner.setEnabled(i>0);
        Skill3Spinner.setEnabled(i>1);
        nmagicSkills=i+1;
    }//GEN-LAST:event_SkillCComboBoxItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        double spellcasting = (Double)SpellcastingSpinner.getValue();;
        //this.nskill = nskill;
        //this.magic_skills = magic_skills;
        double[] magicSkills=new double[nmagicSkills];
        magicSkills[0]=(Double)Skill1Spinner.getValue();
        if(nmagicSkills>1)
            magicSkills[1]=(Double)Skill2Spinner.getValue();
        if(nmagicSkills>2)
            magicSkills[2]=(Double)Skill3Spinner.getValue();
        double shields = (Double)ShieldsSpinner.getValue();
        //this.shieldtype = ShieldsSpinner;
        double armor = (Double)ArmorSpinner.getValue();
        int encumbrance = (Integer)EncumbranceSpinner.getValue();
        //this.size = size;
        int Str = (Integer)StrSpinner.getValue();
        int Int = (Integer)IntSpinner.getValue();
        int spellLvl = (Integer)SpellLvlSpinner.getValue();
        int vehumet=(Integer)(VehumetCheckBox.isSelected() ? VehumetSpinner.getValue() : CrawlCalculator.NOVEHUMET);
        int wizardry=(Integer)(WizardryCheckBox.isSelected() ? WizardrySpinner.getValue() : CrawlCalculator.NOWIZARDRY);
        int wildmagic=(Integer)(WildMagicCheckBox.isSelected() ? WildMagicSpinner.getValue() : CrawlCalculator.NOWILDMAGIC);
        int subduedmagic=(Integer)(SubduedMagicCheckBox.isSelected() ? SubduedMagicSpinner.getValue() : CrawlCalculator.NOSUBDUEDMAGIC);
        boolean hat=HatCheckBox.isSelected();
        CrawlCalculator calc=new CrawlCalculator(spellcasting,nmagicSkills,magicSkills,vehumet,wizardry,wildmagic,subduedmagic,hat,shields,shieldtype,armor,encumbrance,size,Str,Int,spellLvl);
        double res=calc.calculateMiscast();
        ResultLabel.setText(String.valueOf(res));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SpeciesComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SpeciesComboBoxItemStateChanged
       int i=0;
        for(;!SpeciesComboBox.getItemAt(i).equals(evt.getItem());i++){}
        switch(i)
        {
            case 0:
                size=CrawlCalculator.LITTLESPECIES;
                break;
            case 1:
                size=CrawlCalculator.SMALLSPECIES;
                break;
            case 2:
                size=CrawlCalculator.BIGSPECIES;
                break;
            case 3:
                size=CrawlCalculator.NORMALSPECIES;
                break;
        }
    }//GEN-LAST:event_SpeciesComboBoxItemStateChanged

    private void ShieldComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ShieldComboBoxItemStateChanged
         int i=0;
        for(;!ShieldComboBox.getItemAt(i).equals(evt.getItem());i++){}
        switch(i)
        {
            case 0:
                shieldtype=CrawlCalculator.NOSHIELD;
                break;
            case 1:
                shieldtype=CrawlCalculator.BUCKLER;
                break;
            case 2:
                shieldtype=CrawlCalculator.SHIELD;
                break;
            case 3:
                shieldtype=CrawlCalculator.BIGSHIELD;
                break;
        }
        
    }//GEN-LAST:event_ShieldComboBoxItemStateChanged

    private void WildMagicCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_WildMagicCheckBoxItemStateChanged
        WildMagicSpinner.setEnabled(WildMagicCheckBox.isSelected());
    }//GEN-LAST:event_WildMagicCheckBoxItemStateChanged

    private void WizardryCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_WizardryCheckBoxItemStateChanged
        WizardrySpinner.setEnabled(WizardryCheckBox.isSelected());
    }//GEN-LAST:event_WizardryCheckBoxItemStateChanged

    private void VehumetCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_VehumetCheckBoxItemStateChanged
        VehumetSpinner.setEnabled(VehumetCheckBox.isSelected());
    }//GEN-LAST:event_VehumetCheckBoxItemStateChanged

    private void SubduedMagicCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SubduedMagicCheckBoxItemStateChanged
        SubduedMagicSpinner.setEnabled(SubduedMagicCheckBox.isSelected());
    }//GEN-LAST:event_SubduedMagicCheckBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner ArmorSpinner;
    private javax.swing.JSpinner EncumbranceSpinner;
    private javax.swing.JCheckBox HatCheckBox;
    private javax.swing.JSpinner IntSpinner;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JComboBox ShieldComboBox;
    private javax.swing.JSpinner ShieldsSpinner;
    private javax.swing.JSpinner Skill1Spinner;
    private javax.swing.JSpinner Skill2Spinner;
    private javax.swing.JSpinner Skill3Spinner;
    private javax.swing.JComboBox SkillCComboBox;
    private javax.swing.JComboBox SpeciesComboBox;
    private javax.swing.JSpinner SpellLvlSpinner;
    private javax.swing.JSpinner SpellcastingSpinner;
    private javax.swing.JSpinner StrSpinner;
    private javax.swing.JCheckBox SubduedMagicCheckBox;
    private javax.swing.JSpinner SubduedMagicSpinner;
    private javax.swing.JCheckBox VehumetCheckBox;
    private javax.swing.JSpinner VehumetSpinner;
    private javax.swing.JCheckBox WildMagicCheckBox;
    private javax.swing.JSpinner WildMagicSpinner;
    private javax.swing.JCheckBox WizardryCheckBox;
    private javax.swing.JSpinner WizardrySpinner;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner5;
    // End of variables declaration//GEN-END:variables
}
